services:
  watchtower:
    image: containrrr/watchtower
    container_name: sat-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Credenciales de Docker (Usa la variable DOCKER_CONFIG_PATH o busca en la carpeta del usuario actual)
      - ${USERPROFILE}\.docker\config.json:/config.json:ro
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - DOCKER_API_VERSION=1.41
      - WATCHTOWER_LOG_LEVEL=info
    command: sat-api sat-frontend
