services:
  watchtower:
    image: containrrr/watchtower
    container_name: sat-watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Si tu repositorio es privado, necesitaremos configurar el config.json de docker
      #- /home/user/.docker/config.json:/config.json
    environment:
      - WATCHTOWER_POLL_INTERVAL=300 # Revisa cada 5 minutos (300 seg)
      - WATCHTOWER_CLEANUP=true      # Borra las imágenes viejas para no llenar el disco
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - DOCKER_API_VERSION=1.35      # Compatibilidad con Docker Desktop local
    command: sat-api sat-frontend
