# SonarQube Configuration File
# Mapea y configura las exclusiones para el análisis de calidad de código.

sonar.projectKey=IngJoseBracamonte_Sistema2020Excelencia
sonar.projectName=Sistema2020Excelencia

# Excluir el sistema Legacy y Conexion.cs de los análisis de calidad y vulnerabilidades
sonar.exclusions=**/Conexiones/DbConnect/Conexion.cs,**/Conexion.cs,**/Laboratorio/**
