# SonarQube Configuration File
# Mapea y configura las exclusiones para el análisis de calidad de código.

sonar.projectKey=IngJoseBracamonte_Sistema2020Excelencia
sonar.projectName=Sistema2020Excelencia

# Excluir los módulos Legacy protegidos de los análisis de calidad y vulnerabilidades.
sonar.exclusions=**/SistemaLegacy/**,**/Conexiones/**,**/Laboratorio/**,**/Anviz/**,**/OA99/**,**/Conexion.cs
