// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaSatHospitalario.Infrastructure.Persistence.Legacy;

#nullable disable

namespace SistemaSatHospitalario.Infrastructure.Persistence.Legacy.Migrations
{
    [DbContext(typeof(Sistema2020LegacyDbContext))]
    [Migration("20260330153637_AddResultadosPacientePK")]
    partial class AddResultadosPacientePK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.DatosPersonalesLegacy", b =>
                {
                    b.Property<int>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoCelular")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoTelefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Fecha")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TipoCorreo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Visible")
                        .HasColumnType("int");

                    b.HasKey("IdPersona");

                    b.ToTable("datospersonales", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.OrdenLegacy", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<int>("EstadoDeOrden")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoraIngreso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IDConvenio")
                        .HasColumnType("int");

                    b.Property<int>("IDTasa")
                        .HasColumnType("int");

                    b.Property<int>("IdCierreDeCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int>("Muestra")
                        .HasColumnType("int");

                    b.Property<int>("NumeroDia")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioF")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Usuario")
                        .HasColumnType("int");

                    b.Property<int>("VALIDADA")
                        .HasColumnType("int");

                    b.HasKey("IdOrden");

                    b.ToTable("Orden", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.PerfilLegacy", b =>
                {
                    b.Property<int>("IdPerfil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPerfil"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioDOlar")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPerfil");

                    b.ToTable("Perfiles", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.PerfilesAnalisisLegacy", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int");

                    b.Property<int>("IdOrganizador")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.HasKey("IdDetalle");

                    b.ToTable("PerfilesAnalisis", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.PerfilesFacturadosLegacy", b =>
                {
                    b.Property<int>("IdFacturado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdFacturado"));

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdPerfil")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioTotal")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdFacturado");

                    b.ToTable("PerfilesFacturados", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Legacy.ResultadosPacienteLegacy", b =>
                {
                    b.Property<int>("IdResultadoPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdResultadoPaciente"));

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<int?>("Enviado")
                        .HasColumnType("int");

                    b.Property<int?>("EstadoDeResultado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaIngreso")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("HoraImpresion")
                        .HasColumnType("longtext");

                    b.Property<string>("HoraIngreso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HoraValidacion")
                        .HasColumnType("longtext");

                    b.Property<int>("IDOrganizador")
                        .HasColumnType("int");

                    b.Property<int>("IdAnalisis")
                        .HasColumnType("int");

                    b.Property<int>("IdConvenio")
                        .HasColumnType("int");

                    b.Property<int>("IdOrden")
                        .HasColumnType("int");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int?>("Lineas")
                        .HasColumnType("int");

                    b.Property<int?>("MultiplesValores")
                        .HasColumnType("int");

                    b.Property<int>("PorEnviar")
                        .HasColumnType("int");

                    b.Property<int?>("Recibido")
                        .HasColumnType("int");

                    b.Property<string>("Unidad")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorMayor")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorMenor")
                        .HasColumnType("longtext");

                    b.Property<string>("ValorResultado")
                        .HasColumnType("longtext");

                    b.HasKey("IdResultadoPaciente");

                    b.ToTable("ResultadosPaciente", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
