export const HONORARIO_CATEGORIAS = {
    CONSULTA: 'CONSULTA',
    RX: 'RX',
    INFORME: 'INFORME',
    CITOLOGIA: 'CITOLOGIA',
    BIOPSIA: 'BIOPSIA',
    OTROS: 'OTROS'
} as const;

export type HonorarioCategoria = keyof typeof HONORARIO_CATEGORIAS;

export const HONORARIO_ACCIONES = {
    ASIGNACION_MANUAL: 'ASIGNACION_MANUAL',
    ASIGNACION_DEFAULT: 'ASIGNACION_DEFAULT',
    REASIGNACION: 'REASIGNACION',
    CONFIG_CAMBIO: 'CONFIG_CAMBIO'
} as const;
