// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaSatHospitalario.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SistemaSatHospitalario.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SatHospitalarioDbContext))]
    [Migration("20260429165318_AddCatalogoMetodosPago")]
    partial class AddCatalogoMetodosPago
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.BloqueoHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraPautada")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "HoraPautada")
                        .IsUnique();

                    b.ToTable("BloqueosHorarios", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CajaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoInicialBs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicialDivisa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("CajasDiarias", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CatalogoMetodoPago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsUSD")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("EsVuelto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Valor")
                        .IsUnique();

                    b.ToTable("CatalogoMetodosPago", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CitaMedica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<Guid>("CuentaServicioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraPautada")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CuentaServicioId");

                    b.HasIndex("HoraPautada");

                    b.HasIndex("MedicoId");

                    b.ToTable("CitasMedicas", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ConfiguracionGeneral", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ClaveSupervisor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("FacturarLaboratorio")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Iva")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("LogoBase64")
                        .HasColumnType("longtext");

                    b.Property<bool>("MostrarDetalleFacturacion")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Rif")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionGeneral", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ConvenioPerfilPrecio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioHNL")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioUSD")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeguroConvenioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("SeguroConvenioId", "PerfilId")
                        .IsUnique();

                    b.ToTable("ConvenioPerfilPrecios", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaPorCobrar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CompromisoGenerado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("CuentaServicioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAuditoria")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsAudited")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MontoPagadoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotalBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioAuditoria")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CuentaServicioId");

                    b.ToTable("CuentasPorCobrar", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ConvenioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaAuditoria")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaValidacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LegacyOrderId")
                        .HasColumnType("int");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ProcesamientoEstado")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAuditoria")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioValidacion")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FechaCarga");

                    b.HasIndex("PacienteId");

                    b.ToTable("CuentasServicios", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetallePago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("EquivalenteAbonadoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("MontoAbonadoMoneda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReciboFacturaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ReferenciaBancaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FechaPago");

                    b.HasIndex("ReciboFacturaId");

                    b.ToTable("DetallesPago", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetalleServicioCuenta", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<Guid>("CuentaServicioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCarga")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaRealizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Honorario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LegacyMappingId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Realizado")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioCarga")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioTecnico")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CuentaServicioId");

                    b.ToTable("DetallesServicioCuenta", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.Especialidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Especialidades", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.HorarioAtencionMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId");

                    b.ToTable("HorariosAtencionMedicos", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.LogAuditoriaPrecio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AutorizadoPor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("DetalleServicioId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("HonorarioAnterior")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NuevoHonorario")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PrecioModificado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioOriginal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioOperador")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("AuditLogsPrecios", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.Medico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("EspecialidadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("HonorarioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IntervaloTurnoMinutos")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Telefono")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("Medicos", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.OrdenImagen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CuentaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estudio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("PacienteNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProcesadoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.HasIndex("TipoServicio");

                    b.ToTable("OrdenesImagenes", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CedulaPasaporte")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdPacienteLegacy")
                        .HasColumnType("int");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TelefonoContact")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CedulaPasaporte")
                        .IsUnique();

                    b.HasIndex("IdPacienteLegacy")
                        .IsUnique();

                    b.ToTable("PacientesAdmision", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PrecioServicioConvenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<decimal>("PrecioDiferencial")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeguroConvenioId")
                        .HasColumnType("int");

                    b.Property<Guid>("ServicioClinicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("SeguroConvenioId");

                    b.HasIndex("ServicioClinicoId");

                    b.ToTable("PreciosServicioConvenio", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("CajaDiariaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CuentaServicioId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EstadoFiscal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("MontoVueltoUSD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NroControlFiscal")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroRecibo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("TasaCambioDia")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalFacturadoUSD")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("UsuarioEmision")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CajaDiariaId");

                    b.HasIndex("CuentaServicioId");

                    b.ToTable("RecibosFacturas", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReservaTemporal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ExpiracionUtc")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraPautada")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId", "HoraPautada")
                        .IsUnique();

                    b.ToTable("ReservasTemporales", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.SeguroConvenio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rtn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("SegurosConvenios", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("EspecialidadId")
                        .HasColumnType("char(36)");

                    b.Property<decimal>("HonorarioBase")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LegacyMappingId")
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoServicio")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.ToTable("ServiciosClinicos", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioSugerencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicioOrigenId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ServicioSugeridoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ServicioOrigenId");

                    b.HasIndex("ServicioSugeridoId");

                    b.ToTable("serviciossugerencias", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.TasaCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.ToTable("TasaCambio", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.ErrorTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ComentariosResolucion")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MensajeExcepcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MetodoHTTP")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("Resuelto")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ResueltoPor")
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioAsociado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ErrorTickets", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.IncidenciaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("char(36)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IncidenciasHorario", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int?>("ConvenioId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("varchar(21)");

                    b.Property<string>("EstadoFacturacion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumeroLlegadaDiario")
                        .HasColumnType("int");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalCobrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("OrdenesDeServicio", (string)null);

                    b.HasDiscriminator().HasValue("OrdenDeServicio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.RegistroAuditoriaIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaTraza")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IncidenciaIgnoradaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TurnoMedicoId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("RegistroAuditoriaIncidencias", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.TurnoMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("FechaHoraToma")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IgnorandoIncidencia")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid?>("IncidenciaIgnoradaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("TurnosMedicos", (string)null);
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenRX", b =>
                {
                    b.HasBaseType("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio");

                    b.Property<Guid>("AsistenteRxId")
                        .HasColumnType("char(36)");

                    b.Property<string>("EstudioSolicitado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaProcesada")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("Procesada")
                        .HasColumnType("tinyint(1)");

                    b.HasDiscriminator().HasValue("OrdenRX");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CitaMedica", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", "CuentaServicio")
                        .WithMany()
                        .HasForeignKey("CuentaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.Medico", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CuentaServicio");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ConvenioPerfilPrecio", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.SeguroConvenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("SeguroConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaPorCobrar", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", "Cuenta")
                        .WithMany()
                        .HasForeignKey("CuentaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cuenta");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", "Paciente")
                        .WithMany()
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetallePago", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", "ReciboFactura")
                        .WithMany("DetallesPago")
                        .HasForeignKey("ReciboFacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReciboFactura");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetalleServicioCuenta", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", null)
                        .WithMany("Detalles")
                        .HasForeignKey("CuentaServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.HorarioAtencionMedico", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.Medico", null)
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.Medico", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PrecioServicioConvenio", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.SeguroConvenio", "Convenio")
                        .WithMany()
                        .HasForeignKey("SeguroConvenioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioClinicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Convenio");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CajaDiaria", "CajaDiaria")
                        .WithMany()
                        .HasForeignKey("CajaDiariaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", "CuentaServicio")
                        .WithMany()
                        .HasForeignKey("CuentaServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaDiaria");

                    b.Navigation("CuentaServicio");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.Especialidad", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Especialidad");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioSugerencia", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", "ServicioOrigen")
                        .WithMany("Sugerencias")
                        .HasForeignKey("ServicioOrigenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", "ServicioSugerido")
                        .WithMany()
                        .HasForeignKey("ServicioSugeridoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServicioOrigen");

                    b.Navigation("ServicioSugerido");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", null)
                        .WithMany("Ordenes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CuentaServicios", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.Navigation("DetallesPago");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ServicioClinico", b =>
                {
                    b.Navigation("Sugerencias");
                });
#pragma warning restore 612, 618
        }
    }
}
