// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaSatHospitalario.Infrastructure.Persistence.Contexts;

#nullable disable

namespace SistemaSatHospitalario.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SatHospitalarioDbContext))]
    partial class SatHospitalarioDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Admision")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CajaDiaria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MontoInicialBs")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoInicialDivisa")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CajasDiarias", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetallePago", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("EquivalenteAbonadoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontoAbonadoMoneda")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ReciboFacturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenciaBancaria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReciboFacturaId");

                    b.ToTable("DetallesPago", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CedulaPasaporte")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreCorto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TelefonoContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CedulaPasaporte")
                        .IsUnique();

                    b.ToTable("PacientesAdmision", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstadoFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NroControlFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrdenServicioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TasaCambioDia")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("TurnoCajeroId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrdenServicioId");

                    b.HasIndex("TurnoCajeroId");

                    b.ToTable("RecibosFacturas", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.SeguroConvenio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeCobertura")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("SegurosConvenios", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.TurnoCajero", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CajaDiariaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CajeroUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CajaDiariaId");

                    b.ToTable("TurnosCajero", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.IncidenciaHorario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreadoPor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IncidenciasHorario", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConvenioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("EstadoFacturacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombrePaciente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumeroLlegadaDiario")
                        .HasColumnType("int");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoIngreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCobrado")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("OrdenesDeServicio", "Admision");

                    b.HasDiscriminator().HasValue("OrdenDeServicio");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.RegistroAuditoriaIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaTraza")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IncidenciaIgnoradaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OperadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TurnoMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RegistroAuditoriaIncidencias", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.TurnoMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaHoraToma")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IgnorandoIncidencia")
                        .HasColumnType("bit");

                    b.Property<Guid?>("IncidenciaIgnoradaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("TurnosMedicos", "Admision");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenRX", b =>
                {
                    b.HasBaseType("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio");

                    b.Property<Guid>("AsistenteRxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EstudioSolicitado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaProcesada")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Procesada")
                        .HasColumnType("bit");

                    b.HasDiscriminator().HasValue("OrdenRX");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.DetallePago", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", "ReciboFactura")
                        .WithMany("DetallesPago")
                        .HasForeignKey("ReciboFacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReciboFactura");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio", "OrdenServicio")
                        .WithMany()
                        .HasForeignKey("OrdenServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.TurnoCajero", "TurnoCajero")
                        .WithMany("Recibos")
                        .HasForeignKey("TurnoCajeroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrdenServicio");

                    b.Navigation("TurnoCajero");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.TurnoCajero", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.CajaDiaria", "CajaDiaria")
                        .WithMany("Turnos")
                        .HasForeignKey("CajaDiariaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CajaDiaria");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.OrdenDeServicio", b =>
                {
                    b.HasOne("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", null)
                        .WithMany("Ordenes")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.CajaDiaria", b =>
                {
                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.PacienteAdmision", b =>
                {
                    b.Navigation("Ordenes");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.ReciboFactura", b =>
                {
                    b.Navigation("DetallesPago");
                });

            modelBuilder.Entity("SistemaSatHospitalario.Core.Domain.Entities.Admision.TurnoCajero", b =>
                {
                    b.Navigation("Recibos");
                });
#pragma warning restore 612, 618
        }
    }
}
