name: Docker CI/CD

on:
  push:
    branches: [ "main", "master" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME_API: ${{ github.repository_owner }}/sistema-sat-api
  IMAGE_NAME_FE: ${{ github.repository_owner }}/sistema-sat-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build & Push API
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./src/SistemaSatHospitalario.WebAPI/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_API }}:latest

      # Build & Push Frontend
      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./src/SistemaSatHospitalario.Frontend
          file: ./src/SistemaSatHospitalario.Frontend/Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_FE }}:latest
